//CB>-------------------------------------------------------------------
// 
//   File, Component, Release:
//                  %W%
// 
//   SCCSfile:      %F%
//   Revision:      %I%
//   Date:          %E%
// 
//   DESCRIPTION:
//	«Description»
//   
//<CE-------------------------------------------------------------------

static const char * SCCS_Id_@basename % | sed 's/\./_/g'«type @ twice» = "@(#) %W%, %I%";


#include <@basename % .cc«type @ twice».h>
«other includes»


// «static declarations»


// «private function definitions»


// «protected function definitions»


// «public function definitions»



//CB>-------------------------------------------------------------------
// 
//  DESCRIPTION:
//	«Description»
// 
//<CE
«Class»:: «Class»  (Void)
{
    «»
}


//CB>-------------------------------------------------------------------
// 
//  DESCRIPTION:
//	«Description»
// 
//<CE
«Class»:: ~«Class»  (Void)
{
    «»
}


//CB>-------------------------------------------------------------------
// 
//  DESCRIPTION:
//	«Description»
//   
//<CE
«Class»:: «Class»  (const «Class» & fh)
{
    «»
}


//CB>-------------------------------------------------------------------
// 
//  DESCRIPTION:
//	«Description»
//   
//<CE
«Class»:: «Class» & operator =  (const «Class» & fh)
{
    «»
}


«read ~/etc/std.cc.func for a function template»
